GET http://localhost:3000/users

###

GET http://localhost:3000/users/5ea5f4757ea4572744c19caf

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "Belu",
    "email" : "paasdw@asdh.asd"
}

###
DELETE http://localhost:3000/users/5ea1865687f0421ea8f96397

###

PATCH http://localhost:3000/users/5ea184398b00f62c2cb19b95
Content-Type: application/json

{
    "name" : "Carlos"
}
